#!/bin/bash

. $LKP_SRC/lib/mount.sh
. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/upload.sh
. $LKP_SRC/lib/tests/kvm-unit-tests.sh
. $LKP_SRC/lib/git.sh
. $LKP_SRC/lib/misc-base.sh
. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/tests/build-qemu.sh

QEMU="/bin/qemu-system-x86_64"
[[ -f $QEMU ]] || build_qemu
echo "QEMU: $QEMU"
$QEMU --version || die "fail to get version of $QEMU"

cd $BENCHMARK_ROOT/kvm-unit-tests || die "no $BENCHMARK_ROOT/kvm-unit-tests"

export QEMU

fixup_tests
setup_test_environment || die "failed to setup test environment"

run_tests
exit_code=$?

upload_test_results

[ $exit_code -ne 0 ] && dump_qemu

exit $exit_code
