#!/bin/bash
# - group

. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/debug.sh
. $LKP_SRC/lib/env.sh
. $LKP_SRC/lib/tests/avocado.sh

setup_conf || die "failed to setup config file"
setup_env || die "failed to setup env"

# this could be run before setup_env
[[ $group =~ lkvs ]] && install_lkvs_tests

run_test

upload_files -t results $avocado_result_dir/*
