#!/bin/bash

set -e

[[ -n "$LKP_SRC" ]] || LKP_SRC=$(dirname $(dirname $(readlink -e -v $0)))

. $LKP_SRC/lib/docker.sh

while getopts "i:t:-:" opt; do
	case $opt in
		i)
			opt_image="$OPTARG"
			;;
		t)
			opt_container="$OPTARG"
			;;
		-)
			case "${OPTARG}" in
				container)
					opt_container="${!OPTIND}"
					OPTIND=$((OPTIND + 1))
					;;
				image)
					opt_image="${!OPTIND}"
					OPTIND=$((OPTIND + 1))
					;;
				hostname)
					opt_hostname="${!OPTIND}"
					OPTIND=$((OPTIND + 1))
					;;
				proxy)
					opt_proxy="${!OPTIND}"
					OPTIND=$((OPTIND + 1))
					;;
				*)
					echo "Unknown option --${OPTARG}"
					exit 1
					;;
			esac
			;;
	esac
done

shift $((OPTIND - 1))

opt_hostname=${opt_hostname:-$LKP_DOCKER_HOSTNAME}
opt_test_dir=${opt_test_dir:-$LKP_DOCKER_TEST_DIR}

[[ $opt_container ]] && load_container "$opt_container"

[[ $opt_image ]] || {
	echo "No image specified. Use --image <image_name> to specify an image."
	exit 1
}

cd $LKP_SRC

# Substitution for image names (example: debian/buster -> debian:buster)
# Special for opensuse/leap or opensuse/tumbleweed, does not affect it
# 	(example: opensuse/leap:latest -> opensuse/leap:latest)
if [[ "$opt_image" == opensuse/* ]]; then
	base_image=$(echo "$opt_image" | sed 's|opensuse/\([^/]*\)/|opensuse/\1:|')
else
	base_image=${opt_image//\//:}
fi

cmd="docker build . -f docker/${opt_image%%/*}/Dockerfile -t lkp-tests/${opt_image} --build-arg hostname=${opt_hostname} --build-arg base_image=${base_image}"
[[ $opt_proxy ]] && cmd="$cmd --build-arg http_proxy=${opt_proxy} --build-arg https_proxy=${opt_proxy}"

exec_cmd $cmd
