#!/bin/bash

[[ -n "$LKP_SRC" ]] || LKP_SRC=$(dirname $(dirname $(readlink -e -v $0)))

exec_cmd()
{
	echo "$@"
	"$@"
}

opt_hostname="lkp-docker"

while getopts "i:-:" opt; do
	case $opt in
		i)
			opt_image="$OPTARG"
			;;
		-)
			case "${OPTARG}" in
				image)
					opt_image="${!OPTIND}"
					OPTIND=$((OPTIND + 1))
					;;
				hostname)
					opt_hostname="${!OPTIND}"
					OPTIND=$((OPTIND + 1))
					;;
				proxy)
					opt_proxy="${!OPTIND}"
					OPTIND=$((OPTIND + 1))
					;;
				*)
					echo "Unknown option --${OPTARG}"
					exit 1
					;;
			esac
			;;
	esac
done

shift $((OPTIND - 1))

[[ "$opt_image" ]] || {
	echo "No image specified. Use --image <image_name> to specify an image."
	exit 1
}

cmd="docker build . -f $LKP_SRC/docker/${opt_image%%/*}/Dockerfile -t lkp-tests/${opt_image} --build-arg hostname=${opt_hostname} --build-arg base_image=${opt_image//\//:}"
[[ $opt_proxy ]] && cmd="$cmd --build-arg http_proxy=${opt_proxy} --build-arg https_proxy=${opt_proxy}"

exec_cmd $cmd
