#!/bin/bash

set -e

[[ -n "$LKP_SRC" ]] || LKP_SRC=$(dirname $(dirname $(readlink -e -v $0)))

. $LKP_SRC/lib/docker.sh

while getopts "d:i:-:" opt; do
	case $opt in
		d)
			opt_test_dir="$OPTARG"
			;;
		i)
			opt_image="$OPTARG"
			;;
		-)
			case "${OPTARG}" in
				image)
					opt_image="${!OPTIND}"
					OPTIND=$((OPTIND + 1))
					;;
				hostname)
					opt_hostname="${!OPTIND}"
					OPTIND=$((OPTIND + 1))
					;;
				proxy)
					opt_proxy="${!OPTIND}"
					OPTIND=$((OPTIND + 1))
					;;
				*)
					echo "Unknown option --${OPTARG}"
					exit 1
					;;
			esac
			;;
	esac
done

shift $((OPTIND - 1))

opt_hostname=${opt_hostname:-$LKP_DOCKER_HOSTNAME}
opt_test_dir=${opt_test_dir:-$LKP_DOCKER_TEST_DIR}

[[ "$opt_image" ]] || {
	echo "No image specified. Use --image <image_name> to specify an image."
	exit 1
}

containers="$opt_test_dir/containers"
mkdir -p "$containers"

cat <<EOF > "$containers/$opt_hostname"
image=$opt_image
hostname=$opt_hostname
test_dir=$opt_test_dir
proxy=$opt_proxy
EOF

echo "Container file is stored at $containers/$opt_hostname"
