#!/usr/bin/env ruby
LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.dirname(File.dirname(File.realpath($PROGRAM_NAME))))

require "#{LKP_SRC}/lib/string"

$stdin.each_line do |line|
  case line
  when /wakeup cost \(single/
    puts "wakeup_cost_single_us: #{line.split[3].remove(/us/)}"
  when /wakeup cost \(periodic/
    puts "wakeup_cost_periodic_us: #{line.split[4].remove(/us/)}"
  end
end
