#!/bin/bash

[[ -n "$LKP_SRC" ]] || LKP_SRC=$(dirname $(dirname $(readlink -e -v $0)))

command="$1"
shift

case "$command" in
	attach|build|init|install|rt|run|test)
		$LKP_SRC/docker/$command "$@"
		;;
	*)
		echo "Unknown command $command"
		exit 1
		;;
esac
