#!/bin/sh
# - priority
# - clock
# - interval
# - histogram
# - loops

. $LKP_SRC/lib/reproduce-log.sh

export PATH=$BENCHMARK_ROOT/cyclictest/bin:$PATH

run_test()
{
	log_cmd cyclictest -p $priority -m -c $clock -i $interval -h $histogram -q -l $loops 2>&1
}

run_test
