# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.0', '2.5', '2.7', '3.2']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: bundle install
      - run: rubocop -v
      - run: bundle exec rake code

  test-packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['archlinux/base', 'centos/stream9', 'debian/bookworm', 'fedora/41', 'opensuse/leap', 'rockylinux/9', 'ubuntu/noble']

    steps:
      - uses: actions/checkout@v3
      - name: Build ${{ matrix.image }} image
        run: bin/lkp docker build --image ${{ matrix.image }}
      - name: Test packages on ${{ matrix.image }}
        run: docker run -e DEBIAN_FRONTEND=noninteractive --rm --entrypoint '' lkp-tests/${{ matrix.image }} tools/test-packages.sh
